config:
  - app-rule1-easy-travel-angular: "app-rule1-easy-travel-angular.json"
  - app-rule2-easy-travel-angular: "app-rule2-easy-travel-angular.json"
  - app-rule3-easy-travel-angular: "app-rule3-easy-travel-angular.json"
  - app-rule4-easy-travel-angular: "app-rule4-easy-travel-angular.json"
  - app-rule1-easy-travel-orange: "app-rule1-easy-travel-orange.json"
  - app-rule2-easy-travel-orange: "app-rule2-easy-travel-orange.json"

app-rule1-easy-travel-angular:
  - name: "eztravel/application-web/app-easy-travel-angular.name"
  - applicationidentifier: "eztravel/application-web/app-easy-travel-angular.id"

app-rule2-easy-travel-angular:
  - name: "eztravel/application-web/app-easy-travel-angular.name"
  - applicationidentifier: "eztravel/application-web/app-easy-travel-angular.id"

app-rule3-easy-travel-angular:
  - name: "eztravel/application-web/app-easy-travel-angular.name"
  - applicationidentifier: "eztravel/application-web/app-easy-travel-angular.id"

app-rule4-easy-travel-angular:
  - name: "eztravel/application-web/app-easy-travel-angular.name"
  - applicationidentifier: "eztravel/application-web/app-easy-travel-angular.id"

app-rule1-easy-travel-orange:
  - name: "eztravel/application-web/app-easy-travel-orange.name"
  - applicationidentifier: "eztravel/application-web/app-easy-travel-orange.id"

app-rule2-easy-travel-orange:
  - name: "eztravel/application-web/app-easy-travel-orange.name"
  - applicationidentifier: "eztravel/application-web/app-easy-travel-orange.id"
